name: deploy-main # 파이프라인 이름은 자유롭게

on:
  push:
    branches:
      - main # main 브랜치에 새로운 커밋이 올라왔을 때 실행될 수 있도록
    workflow_dispatch: # 필요한 경우 수동으로 실행할 수도 있도록

jobs:
  deploy:
    runs-on: ubuntu-latest # CI/CD 파이프라인이 실행될 운영체제 환경을 지정
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p -/.ssh
          echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          cat >>~/.ssh/config <<END
          Host playground-umc-7th
            HostName $EC2_HOST
            User $EC2_USER
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END
        env:
          EC2_USER: ubuntu
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy Workspace
        run: |
          ssh playground-umc-7th 'sudo mkdir -p /opt/app'
          ssh playground-umc-7th 'sudo chown ubuntu:ubuntu /opt/app'
          scp -r ./[!.]* playground-umc-7th:/opt/app

      - name: Install dependencies
        run: |
          ssh playground-umc-7th 'npm install --prefix /opt/app/'

      - name: Copy systemd service file
        run: |
          ssh playground-umc-7th '
            echo "[Unit]
            Description=UMC 7th Project
            After=network.target

            [Service]
            User=${USER}
            ExecStart=/usr/bin/npm run dev --prefix /opt/app/
            Restart=always

            [Install]
            WantedBy=multi-user.target" | sudo tee /etc/systemd/system/app.service
          '

      - name: Enable systemd service
        run: |
          ssh playground-umc-7th 'sudo systemctl daemon-reload'
          ssh playground-umc-7th 'sudo systemctl enable app'

      - name: Restart systemd service
        run: |
          ssh playground-umc-7th 'sudo systemctl restart app'
